### ISSUE TITLE
The extension stops downloading Apple Music albums cover art

### ISSUE THREAD

**Issue by kunehenry** [jgchk/better-rym#185]
I'm using Edge browser on MacOS

**Comment by FlorianWolters** [comment]
I can confirm this. I'm using Firefox v114.0.2 and the extension v4.25.0.

**Comment by sc113** [comment]
The extension has also started to extract incorrectly sized images for music videos. Here https://music.apple.com/gr/music-video/on-on-again/1683514891 the original image is 1912x1072, but BetterRYM got 1200x675.

**Comment by FlorianWolters** [comment]
> The extension has also started to extract incorrectly sized images for music videos. Here https://music.apple.com/gr/music-video/on-on-again/1683514891 the original image is 1912x1072, but BetterRYM got 1200x675.

But that is another issue, potentially unrelated to this one. I suggest to create a separate issue for that misbehavior.

In addition: This is a duplicate of #183.

**Comment by FlorianWolters** [comment]
Duplicate of #183

**Comment by jgchk** [comment]
solved in ca74c1460d9368df4d9a259cc2e9d94bb30f2a67

**Comment by jgchk** [comment]
incorrect sizing fixed in 24f39abe1b5cf978366268b04c4a2805403a77df

**Comment by kopytko95** [comment]
Still doesn't work for me even though it seem like the recent version is already on the chrome webstore (shows yesterday's date for last update), reinstalling didn't help

**Comment by jgchk** [comment]
could you send an example link that doesn't work?

**Comment by jgchk** [comment]
may have found this issue: c05d8b690e7e99e60fc459be8fd8399a83809f44

check the update as it comes in today and let me know @kopytko95
